# version include

VERSION          = 0.9.0

QMAKE_TARGET_COMPANY = Mobotix AG
QMAKE_TARGET_PRODUCT = MxSDK
QMAKE_TARGET_DESCRIPTION = IPP-accelerated MxPEG decoding
QMAKE_TARGET_COPYRIGHT = Copyright (C) 2006-2007 Mobotix AG
