# version include

VERSION          = 1.0.0

QMAKE_TARGET_COMPANY = Mobotix AG
QMAKE_TARGET_PRODUCT = MxSDK
QMAKE_TARGET_DESCRIPTION = mxm Qt tools
QMAKE_TARGET_COPYRIGHT = Copyright (C) 2006-2007 Mobotix AG
